# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI test Example

on:
  push:
    branches:
       - feature/*
       - bugfix/*
       - hotfix/*
  pull_request:
    types:
       - opened
    branches:
        - main
        - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
           npm install &&
           npm i -g @angular/cli

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0
      with:
        # The Chromium version to install and use.
        chromium-version: # optional

    - name: Build
      run: ng build --base-href /dani/ --deploy-url /dani/

    - name: Run tests
      run: ng test


  finish:
    needs: build
     steps:
    - name: notify of failure
        if: ${{ failure() }}
        with:
            text: XXX Build failed - Deploy - Server - TEST - Azure Web Apps CI/CD. XXX
    - name: notify of success
        if: ${{ success() }}
        with:
            text: ":heavy_check_mark: Build success - Deploy -  Server - TEST - Azure Web pps CI/CD. :heavy_check_mark:"