# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI test Example

on:
  push:
    branches:
       - feature/*
       - bugfix/*
       - hotfix/*
  pull_request:
    types:
       - opened
    branches:
        - develop

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
          node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
           npm install &&
           npm i -g @angular/cli

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0
      with:
        # The Chromium version to install and use.
        # Google Chrome release channels: stable, beta, dev and canary
        chromium-version:  # optional
    - run: chrome --version

    - name: Build
      run: ng build --base-href /dani/ --deploy-url /dani/

    - name: Run tests
      run: ng test --watch false --code-coverage

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
          retention-days: 5

    - name: Coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: coverage/lcov.info # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)

    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: dist-without-markdown

    - name: The job has succeeded
      if: ${{ success() }}
      run: echo "success !!"
